### ISSUE TITLE
Vista del recurso- Sobra cifra especies

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/dataportal_v2_frontend#110]
Actualizar la vista del recurso de acuerdo al último mockup, la cifra de especies sobra.
Última versión Mockup @javiesgm 
![image](https://user-images.githubusercontent.com/5700527/37736076-e8f7f298-2d1d-11e8-8d13-f219add72575.png)
Versión actual con error
![image](https://user-images.githubusercontent.com/5700527/37736112-03173a94-2d1e-11e8-8fd1-0139360bb8cc.png)

**Comment by johnfra797** [comment]
Listo
