### ISSUE TITLE
Añadir formulario de consultas a las descargas del portal de datos

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/dataportal_v2_frontend#266]
Con el objetivo de poder mapear el uso de los datos descargados desde el Portal se podría incluir provisionalmente un formulario (google forms) mientras se  genera un mecanismo  interno del portal

La intensión es que el Formulario se abra en una página alterna al dar clic en el botón descargar, mientras llega la descarga al correo, o que llegue junto con el correo de descarga.

Envío un borrador del [formulario](https://docs.google.com/forms/d/e/1FAIpQLSe5Z-n511-CzgMJ4iYAfebkU5KvypjcNGsBVWq3W9XuNvH_jw/viewform
) para discutir en el sprint o en una reunión posterior. @javiesgm @leobuitrago

**Comment by iraidamercedes** [comment]
migrado a gitlab
