### ISSUE TITLE
Crear Molécula para ver resumen de Registro

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/dataportal_v2_frontend#38]
Este resumen debe tener la información básica a visualizar en un registro en diferentes lugares, como los mapas o las tablas de resumen

**Comment by jag2kn** [comment]
¿Qué parámetros deben mostrarse en este Organismo?

**Comment by valegrajales** [comment]
Ver referencia resumen. Revisar lo levantado en sesión de requerimientos.
