### ISSUE TITLE
Bloque Estadísticas del Portal de Datos

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/dataportal_v2_frontend#41]
Desarrollar un organismo que muestre la información de Estadísticas que tiene el portal

**Comment by jag2kn** [comment]
¿Cuales variables se van a mostrar?

**Comment by valegrajales** [comment]
Es necesario definir las estadísticas que van a ser mostradas. Probablemente esto requiere levantamiento de requerimientos.
