### ISSUE TITLE
Logos de los canales de participación

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#44]
En los lineamientos generales se describen claramente las dimensiones y proporsiones de los logosímbolos de cada canal de participación del SiB Colombia. 

[Lineamientos generales v1.1.pdf](https://github.com/SIB-Colombia/dataportal_v2_frontend/files/1218277/Lineamientos.generales.v1.1.pdf)

![captura de pantalla 2017-08-11 a la s 10 12 42 a m](https://user-images.githubusercontent.com/14220404/29219539-f43e78ce-7e7d-11e7-8ead-508d0f3673a5.png)

Hay diferencias entre los portales y errores en las proporciones: 
![captura de pantalla 2017-08-11 a la s 10 15 46 a m](https://user-images.githubusercontent.com/14220404/29219582-14bc8ece-7e7e-11e7-9afd-b619f2d78dab.png)

![captura de pantalla 2017-08-11 a la s 10 16 13 a m](https://user-images.githubusercontent.com/14220404/29219615-269e4268-7e7e-11e7-961b-0c49c601f234.png)

**Comment by jag2kn** [comment]
@javiesgm por favor generar unos iconos para la cabecera sin los espacios al rededor del logo es decir como la imagen adjunta:

![real](https://user-images.githubusercontent.com/321637/29691317-2fa2bda4-88f0-11e7-8cff-cd36bd39d508.png)

**Comment by javiesgm** [comment]
@jag2kn Listos!
disponibles en: 
https://docs.google.com/spreadsheets/d/1jIUW1MsGqJ3DPlWhtMLKR0Rc2wplqzype2C0QZRwuOg/edit?usp=sharing

**Comment by jag2kn** [comment]
Hecho
