### ISSUE TITLE
Proporciones de títulos, íconos y en general aspecto del home

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#45]
Las páginas iniciales de los canales de participación deben guardar las mismas proporciones para títulos, tamaño de íconos ("Explora por grupos biológicos") y footer. En este momento catálogo y portal de datos son diferentes. El que está mejor en este momento es el del catálogo.

Catálogo: 
![catalogo de la biodiversidad](https://user-images.githubusercontent.com/14220404/29219972-41212eec-7e7f-11e7-9ed8-5058b2164a92.png)

Portal de datos: 
![portal de datos](https://user-images.githubusercontent.com/14220404/29220010-6166a740-7e7f-11e7-96d7-096c55b81470.png)

**Comment by jag2kn** [comment]
Se trabajó para implementar los estilos del archivo de Lineamientos Generales
