### ISSUE TITLE
Barra de canales de participación

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#46]
La barra del footer para los canales de participación **debe aparecer y comportarse igual para todos los canales.** 
En este momento solo aparece en portal de datos y de manera diferente a como se envió en los mockups. Es importante que los logosímbolos de los canales de participación sean exactamente iguales a los proporcionados en los mockups y guarden las proporciones allí documentadas. 
 
Portal de datos versión web: 
![captura de pantalla 2017-08-11 a la s 10 26 15 a m](https://user-images.githubusercontent.com/14220404/29220202-f5e593ae-7e7f-11e7-9e4a-72ea935f5fcf.png)

Portal de datos versión responsive: 
![captura de pantalla 2017-08-11 a la s 10 30 26 a m](https://user-images.githubusercontent.com/14220404/29220264-2174f726-7e80-11e7-84b7-cc164c87d68a.png)
![captura de pantalla 2017-08-11 a la s 10 30 08 a m](https://user-images.githubusercontent.com/14220404/29220265-217ba936-7e80-11e7-9282-376d6024f929.png)

**Comment by jag2kn** [comment]
Se ajustaron los estilos para las pantallas estándar
