### ISSUE TITLE
Diseño de tabla de registros 

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#47]
Hay diferencias evidentes entre los mockups y la forma en la que se está viendo la tabla de registros al disparar una búsqueda: http://design.portal.lumon.com.co/search/table?q=a

1. Tamaño de fuentes (Registros biológicos/ TABLA, MAPA, ESPECIES, RECURSOS, PUBLICADORES).
2. Anchos de columnas en las tablas deben ser diferentes según el contenido que contienen. 
3. Si el contenido de una celda supera el ancho de la columna que la contiene no deben crearse renglones adicionales. Debe cerrar con puntos suspensivos. 
4. (TABLA, MAPA, ESPECIES, RECURSOS, PUBLICADORES) va en el mismo "renglón" con el botón de descarga. Están en niveles diferentes. 

Mockups: 
![captura de pantalla 2017-08-11 a la s 10 34 28 a m](https://user-images.githubusercontent.com/14220404/29220469-baab9a08-7e80-11e7-8b02-614f5374d324.png)

http://design.portal.lumon.com.co: 
![captura de pantalla 2017-08-11 a la s 10 32 32 a m](https://user-images.githubusercontent.com/14220404/29220496-d338f016-7e80-11e7-919e-053913e98488.png)

**Comment by javiesgm** [comment]
@jag2kn  Si bien hay mejoras en la visualización, aun hay cosas por corregir. 

1. Ancho de tabla cuando se cierra el panel de filtros: 
Sugiero que el ancho de la tabla sea de un 90% para aprovechar pantallas de alta resolución. 
adjunto img: 
![comportamiento-tabla-sin-filtros](https://user-images.githubusercontent.com/14220404/29892994-328b053a-8d96-11e7-9d38-667c224f4509.png)

2. La alineación y comportamiento de los botones sobre la tabla sigue siendo extraño. 
Adjunto img donde se evidencia el ajuste por hacer:  
![tabla-registros](https://user-images.githubusercontent.com/14220404/29893153-c5593e2c-8d96-11e7-9a3e-8a0739a172bc.png)

Adicionalmente, cuando se oculta la barra de filtros hay un salto extraño en los botones que van sobre la linea gris de la tabla, y el título de resultados de búsqueda. Sugiero que estos botones y el título conserven su posición para que lo único que se modifique sea el ancho de la tabla. 
adjunto GIF: 
![comportamiento-tabla](https://user-images.githubusercontent.com/14220404/29893410-9937006c-8d97-11e7-92bf-227b7a29d528.gif)



3. El tamaño de la fuente para los resultados de búsqueda es 21px

**Comment by javiesgm** [comment]
- Los nombres de los departamentos deben ajustarse a una línea y si son muy largos van con puntos suspensivos

- Adicionalmente el color de resalte sobre las filas de las tablas debe ir con el mismo color de fondo de la barra de búsqueda y no en amarillo: creo que es #F2FBFB aunque la plataforma me bota el color en RGB: rgb(241, 248, 247)

**Comment by jag2kn** [comment]
Hecho
