### ISSUE TITLE
Ajustar la visualización modo grilla de publicadores según mockups

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#50]
Actual: 
![captura de pantalla 2017-08-11 a la s 10 46 20 a m](https://user-images.githubusercontent.com/14220404/29220950-745334e2-7e82-11e7-871c-090eb6e1130c.png)

Mockups: 
![captura de pantalla 2017-08-11 a la s 10 47 40 a m](https://user-images.githubusercontent.com/14220404/29220968-8980cae6-7e82-11e7-9912-f6e87b4b4650.png)

**Comment by cosmicgarden** [comment]
Se debe mejorar el responsive
![image](https://user-images.githubusercontent.com/4042071/29223409-11b2908a-7e8c-11e7-8299-40437b8f6c62.png)

**Comment by jag2kn** [comment]
Hecho
