### ISSUE TITLE
Ajustar proporciones en página de publicador

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#51]
Ajustar espacios y tamaños de fuentes según los mockups. 

Mockups: 
![captura de pantalla 2017-08-11 a la s 10 59 08 a m](https://user-images.githubusercontent.com/14220404/29221366-20890a7e-7e84-11e7-9e51-cda6838e7d49.png)

Actual: 
![portal de datos- publicador](https://user-images.githubusercontent.com/14220404/29221395-3b7fd10a-7e84-11e7-9009-4c70ddcbf6e4.png)

**Comment by jag2kn** [comment]
Hecho
