### ISSUE TITLE
Ajustar y garantizar persistencia de la posición de logo portal de datos

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#52]
Tamaño y ubicación del logo en página inicial: 
![captura de pantalla 2017-08-11 a la s 11 01 28 a m](https://user-images.githubusercontent.com/14220404/29221462-7676a112-7e84-11e7-8779-a5a54dade64e.png)

Tamaño y ubicación del logo en página de publicador:
![captura de pantalla 2017-08-11 a la s 11 02 33 a m](https://user-images.githubusercontent.com/14220404/29221497-9c65b282-7e84-11e7-9ec2-1a439e816f1f.png)

**Comment by jag2kn** [comment]
Hecho
