### ISSUE TITLE
Ajustar modo "grilla" de la búsqueda por recursos

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#53]
Mockups: 
![captura de pantalla 2017-08-11 a la s 11 04 11 a m](https://user-images.githubusercontent.com/14220404/29221556-d496300a-7e84-11e7-9088-a9d5405ba0d4.png)

Actual: 
![captura de pantalla 2017-08-11 a la s 11 04 34 a m](https://user-images.githubusercontent.com/14220404/29221564-e1bb92b6-7e84-11e7-9b90-0a6d7fdc28cb.png)

**Comment by jag2kn** [comment]
Hecho
