### ISSUE TITLE
Comportamiento responsive tabla Registros

### ISSUE THREAD

**Issue by cosmicgarden** [SIB-Colombia/dataportal_v2_frontend#54]
La tabla de registros biológicos no tienen un buen comportamiento responsive
![image](https://user-images.githubusercontent.com/4042071/29223199-564708da-7e8b-11e7-8340-786226737106.png)

![image](https://user-images.githubusercontent.com/4042071/29223226-6fb3f6d4-7e8b-11e7-89af-1960019fec97.png)

**Comment by jag2kn** [comment]
Hecho
