### ISSUE TITLE
Iconos grises "explora a través de grupos biológicos" del portal de datos

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#56]
En este [archivo](https://docs.google.com/spreadsheets/d/1jIUW1MsGqJ3DPlWhtMLKR0Rc2wplqzype2C0QZRwuOg/edit#gid=1020452772) están los íconos en color gris para la ventana de "Explora a través de grupos biológicos". En la pestaña portal de datos.

**Comment by jag2kn** [comment]
Hecho
