### ISSUE TITLE
Imagen de fondo para Portal de datos

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#60]
Img:
https://s3.amazonaws.com/sib-resources/images/portal-de-datos/jpg/fondo-pd.jpg

Sin embargo, sería conveniente revisar la posibilidad de generar una imagen de fondo, de manera automatizada, en función de los registros que haya en el portal.

**Comment by jag2kn** [comment]
Hecho, se generó el issue #92
