### ISSUE TITLE
LOGOS - Canales de participación - SiB Colombia

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#62]
En este documento están los logos para los canales de participación del SiB Colombia, en la pestaña "Logos canales de participación":
https://docs.google.com/spreadsheets/d/1jIUW1MsGqJ3DPlWhtMLKR0Rc2wplqzype2C0QZRwuOg/edit?usp=sharing

Van en color y en blanco. 
También está el símbolo solo. 

Van en png y svg.

**Comment by jag2kn** [comment]
Hecho
