### ISSUE TITLE
FOOTER - Canales de participación SiB colombia

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#64]
Dimensiones y proporciones para el footer de TODOS los canales de participación SiB Colombia

Img: 
![footer-canales](https://user-images.githubusercontent.com/14220404/29576249-c5d155bc-872c-11e7-805e-9f6897f6abe4.jpg)

PDF: 
[footer-canales.pdf](https://github.com/SIB-Colombia/dataportal_v2_frontend/files/1242674/footer-canales.pdf)

**Comment by jag2kn** [comment]
Una pregunta, en caso que la pantalla tenga menos de 1280px como se debe ver el footer? @javiesgm

**Comment by javiesgm** [comment]
@jag2kn 

Menos de 980px: 
IMG:
![responsive-footer-canales-21](https://user-images.githubusercontent.com/14220404/29584977-16698cce-874b-11e7-8cd5-76690ecbd481.png)

Menos de 400px
IMG:
![responsive-footer-canales-22](https://user-images.githubusercontent.com/14220404/29585011-3540bcda-874b-11e7-975b-b67684b0226e.png)
 
PDF:
[responsive-footer-canales.pdf](https://github.com/SIB-Colombia/dataportal_v2_frontend/files/1243216/responsive-footer-canales.pdf)

**Comment by javiesgm** [comment]
@jag2kn por favor tener en cuenta los lineamientos adjuntos en este issue para el comportamiento del footer en los portales. La posición de los "Canales de participación" sigue excediendo la proporción indicada: 66.6%

**Comment by javiesgm** [comment]
Adicionalmente las versiones responsive, necesitan ajustarse. 
La sección con el llamado a participar se comporta erráticamente y los elementos no se organizan como está estipulado en los mockups. 

imgs:
![captura de pantalla 2017-08-30 a la s 9 19 36 a m](https://user-images.githubusercontent.com/14220404/29877175-8744c188-8d64-11e7-94bf-e32a5816c9fd.png)
![captura de pantalla 2017-08-30 a la s 9 19 24 a m](https://user-images.githubusercontent.com/14220404/29877176-87496468-8d64-11e7-9b03-f53ecda567a1.png)
![captura de pantalla 2017-08-30 a la s 9 19 10 a m](https://user-images.githubusercontent.com/14220404/29877174-8741d8ec-8d64-11e7-94cf-167e36a44b06.png)

**Comment by jag2kn** [comment]
Solucionado
