### ISSUE TITLE
VER EN TABLA - incluir en vista de recurso

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#70]
Adjunto img de como debe verse el "Ver en tabla" en la vista de recurso. 
Este ajuste aplica para portal de datos y para colecciones en línea solamente. 

img: 
![captura de pantalla 2017-08-30 a la s 10 02 52 a m](https://user-images.githubusercontent.com/14220404/29879417-9b595188-8d6a-11e7-8503-92cc6394b494.png)

**Comment by jag2kn** [comment]
Hecho, Ver en tabla carga los registros del recurso

**Comment by javiesgm** [comment]
@jag2kn, este enlace debe direccionar a búsqueda por registros para poder filtrar la información en caso de que el usuario lo requiera. Solamente en listas, el ver en tabla carga la información ahí mismo. ¿Si queda claro?
