### ISSUE TITLE
Incluir franjas grises en detalle de elemento DwC para facilitar lectura

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#73]
Ejemplo Colecciones Biológicas en Línea
 ![captura de pantalla 2017-12-13 a la s 3 22 58 p m](https://user-images.githubusercontent.com/14220404/33960692-8888391e-e019-11e7-8334-0cc67904b35c.png)
Ajustar según mockps

**Comment by jag2kn** [comment]
Hecho 
![lineas](https://user-images.githubusercontent.com/321637/34021944-6dc4867c-e10a-11e7-9358-9c2a8b585bc6.png)
