### ISSUE TITLE
Mapa en búsqueda por registros - BUG

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#79]
![captura de pantalla 2017-12-13 a la s 4 02 46 p m](https://user-images.githubusercontent.com/14220404/33962309-2675d00a-e01f-11e7-9a61-7530a3d7081a.png)

**Comment by javiesgm** [comment]
Además unificar visualización. Va en puntos

**Comment by jag2kn** [comment]
Solucionado el bug del mapa 
![mapa](https://user-images.githubusercontent.com/321637/34022345-bae02810-e10c-11e7-81d7-eb273ef73217.png)

**Comment by jag2kn** [comment]
Se unificó la visualización por puntos

Toca evaluar esto ya que en los casos que se tienen pocos registros se ven muy pequeños estos puntos
@javiesgm @leobuitrago
