### ISSUE TITLE
Barra lateral de filtros persistente para todos los canales de participación

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#89]
![captura de pantalla 2017-12-13 a la s 4 32 08 p m](https://user-images.githubusercontent.com/14220404/33963572-62fa7874-e023-11e7-97e3-e4a84796da5e.png)

Ejemplo GBIF https://www.gbif.org/occurrence/search?advanced=1
![filtrospersistentes](https://user-images.githubusercontent.com/14220404/33963657-a828cfcc-e023-11e7-811f-89b6174ad9af.gif)

**Comment by jag2kn** [comment]
Hecho
