### ISSUE TITLE
Eliminar LISTAS de los tabs de filtro en búsqueda por Recursos

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#90]
![captura de pantalla 2017-12-13 a la s 4 36 32 p m](https://user-images.githubusercontent.com/14220404/33963717-ed629f28-e023-11e7-8b16-32bc12852ce4.png)

**Comment by jag2kn** [comment]
Hecho
![mapafondo](https://user-images.githubusercontent.com/321637/34023885-4abd513a-e115-11e7-89ea-95b5aeed3363.png)
