### ISSUE TITLE
Modificar mapa de fondo para miniatura de Recursos

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/dataportal_v2_frontend#91]
Aplica para Listas y colecciones también. 

URL: https://s3.amazonaws.com/sib-resources/images/portal-de-datos/png/Tile-map2.png

**Comment by jag2kn** [comment]
Hecho 
![mapafondo](https://user-images.githubusercontent.com/321637/34023872-2f100c34-e115-11e7-894c-33937e425918.png)
